#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
set -eu
LC_ALL=C
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: must be root\e[00m"
	exit 1
fi
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
echo "$BASHPID" > /run/$(basename $0).pid
mkdir -p /etc/sysctl.d
name="/etc/sysctl.d/10-calc-mem.conf"
memor=$(grep MemTotal /proc/meminfo | awk '{print $2}')
mb=$(( $memor * 1024 ))
mf=$(( $mb / 1024 * 0,01 ))
fm=$(( $mb / 4194304 * 256 ))
mo=$(( $mb * 0,10 / 65536 ))
mt=$(( $fm * 2 ))
page_size=$(getconf PAGE_SIZE)
phys_pages=$(getconf _PHYS_PAGES)
shmall=$(( $phys_pages / 2 ))
shmmax=$(( $shmall * $page_size ))
echo "kernel.shmmax = $shmmax" > "$name"
echo "kernel.shmall = $shmall" >> "$name"
echo "vm.min_free_kbytes = $mf" >> "$name"
echo "fs.file-max = $fm" >> "$name"
echo "net.ipv4.tcp_max_orphans = $mo" >> "$name"
echo "net.ipv4.tcp_max_tw_buckets = $mt" >> "$name"
if (( $memor < 1024000 )); then
        echo "vm.dirty_ratio = 25" >> "$name"
        echo "vm.dirty_background_ratio = 15" >> "$name"
        echo "vm.dirty_expire_centisecs = 750" >> "$name"
        echo "vm.dirty_writeback_centisecs = 125" >> "$name"
else
        if (( $memor > 4096000 )); then
            echo "vm.swappiness = 10" >> "$name"
            echo "vm.vfs_cache_pressure = 50" >> "$name"
        fi
        if (( $memor < 8192000 )); then
            echo "vm.dirty_ratio = 12" >> "$name"
            echo "vm.dirty_background_ratio = 10" >> "$name"
            echo "vm.dirty_expire_centisecs = 1500" >> "$name"
            echo "vm.dirty_writeback_centisecs = 250" >> "$name"
        else
            echo "vm.dirty_ratio = 3" >> "$name"
            echo "vm.dirty_background_ratio = 5" >> "$name"
            echo "vm.dirty_expire_centisecs = 3000" >> "$name"
            echo "vm.dirty_writeback_centisecs = 500" >> "$name"
        fi
fi
sysctl -p
cat "$name"
echo -e "\e[00;1;92mFinished...\e[00m"
rm -f /run/$(basename $0).pid
